1102h
fd1-53-17/boltwest pull request #3
Opened 2017-11-02 08:53 UTC by boltwest

@antonkulakov-it 
please review

2017-11-03 04:15 UTC, antonkulakov-it requested changes
заменить кавычки, минусы на мнемоники.

2017-11-03 04:15 UTC, antonkulakov-it commented on dz1/vechno_student.html
> +которую студенчество по праву считает  "своей",  хотя  написана<br>
кавычки не заменены на мнемонику

2017-11-03 04:15 UTC, antonkulakov-it commented on dz1/vechno_student.html
> +ней есть слова, которые многое объясняют: "Потому что нам<br>
мнемоники

2017-11-03 04:15 UTC, antonkulakov-it commented on dz1/vechno_student.html
> +мотив был потом вплетен Берлиозом в  "Осуждение  Фауста".  Лист<br>
мнемоники

2017-11-07 13:33 UTC, boltwest commented
@antonkulakov-it 
please review

2017-11-08 04:00 UTC, antonkulakov-it approved these changes

2017-11-08 04:00 UTC, merged